# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0-SNAPSHOT
group=btpos.mcmods.examplemod
java_version=21

# Common
minecraft_version=1.21.8
mod_name=Example Mod
mod_author=ByThePowerOfScience
mod_id=examplemod
license=CC0-1.0
credits=BlameJared
description=ByThePowerOfScience's 1.21.8 Kotlin variant of BlameJared's Multiloader Template
minecraft_version_range=[1.21.8, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Fabric
fabric_version=0.130.0+1.21.8
fabric_loader_version=0.17.0

# Forge
forge_version=55.0.1
forge_loader_version_range=[55,)

# NeoForge
neoforge_version=21.8.25
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
